# Generated by Django 3.2.25 on 2025-12-07 18:57

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ton_address', models.CharField(blank=True, max_length=128)),
                ('bio', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('deals_completed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer Profile',
                'verbose_name_plural': 'Buyer Profiles',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price_max_rub', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('buyer_fee_rub', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('service_fee_rub', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('insurance_rub', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('item_price_ton', models.DecimalField(decimal_places=9, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1E-9'))])),
                ('buyer_fee_ton', models.DecimalField(decimal_places=9, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1E-9'))])),
                ('service_fee_ton', models.DecimalField(decimal_places=9, default=Decimal('0E-9'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0E-9'))])),
                ('insurance_ton', models.DecimalField(decimal_places=9, default=Decimal('0E-9'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0E-9'))])),
                ('status', models.CharField(choices=[('FUNDED', 'Средства зарезервированы'), ('PURCHASED', 'Товар куплен'), ('SHIPPED', 'Товар отправлен'), ('COMPLETED', 'Завершена'), ('CANCELLED_REFUND_CUSTOMER', 'Отменена (возврат заказчику)'), ('CANCELLED_PAY_BUYER', 'Отменена (выплата байеру)'), ('DISPUTE', 'Спор')], default='FUNDED', max_length=32)),
                ('purchase_deadline', models.DateTimeField()),
                ('ship_deadline', models.DateTimeField()),
                ('confirm_deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_deals', to='core.buyerprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=255)),
                ('shipping_provider', models.CharField(blank=True, max_length=128)),
                ('receipt_photo_url', models.URLField(blank=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='core.deal')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('provider_payment_id', models.CharField(blank=True, max_length=128)),
                ('amount_rub', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('PENDING', 'В обработке'), ('SUCCESS', 'Успешно'), ('FAILED', 'Ошибка'), ('REFUNDED', 'Возвращён')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='core.deal')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('store_link', models.URLField(blank=True)),
                ('store_city', models.CharField(max_length=64)),
                ('store_country', models.CharField(max_length=64)),
                ('max_item_price_rub', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('buyer_fee_rub', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('service_fee_rub', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('insurance_rub', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('OPEN', 'Открыта'), ('MATCHED', 'Найден байер'), ('PAID', 'Оплачена'), ('CANCELLED', 'Отменена'), ('COMPLETED', 'Завершена')], default='OPEN', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Request',
                'verbose_name_plural': 'Order Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnchainDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=128)),
                ('metadata_hash_hex', models.CharField(max_length=128)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onchain_deal', to='core.deal')),
            ],
            options={
                'verbose_name': 'Onchain Deal',
                'verbose_name_plural': 'Onchain Deals',
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.IntegerField(choices=[(1, 'Товар не получен'), (2, 'Товар повреждён'), (3, 'Товар не соответствует описанию'), (99, 'Другое')])),
                ('description', models.TextField()),
                ('resolution', models.CharField(choices=[('PENDING', 'В рассмотрении'), ('REFUND_CUSTOMER', 'Возврат заказчику'), ('PAY_BUYER', 'Выплата байеру'), ('SPLIT', 'Разделение'), ('RESOLVED', 'Разрешён')], default='PENDING', max_length=32)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='core.deal')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='core.orderrequest'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='core.deal')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'ordering': ['-created_at'],
                'unique_together': {('deal', 'rated_by')},
            },
        ),
    ]
