# Generated by Django 3.2.25 on 2025-12-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('NEW', 'Создана (байер выбран, оплата не выполнена)'), ('FUNDED', 'Escrow на блокчейне профинансирован'), ('PURCHASED', 'Товар куплен'), ('SHIPPED', 'Товар отправлен'), ('COMPLETED', 'Завершена'), ('CANCELLED_REFUND_CUSTOMER', 'Отменена (возврат заказчику)'), ('CANCELLED_PAY_BUYER', 'Отменена (выплата байеру)'), ('DISPUTE', 'Спор')], default='NEW', max_length=32),
        ),
    ]
