# Generated by Django 3.2.25 on 2025-12-09 20:12

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_deal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='actual_item_price_rub',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена товара по чеку (заполняется после покупки)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Фактическая цена покупки'),
        ),
        migrations.AddField(
            model_name='deal',
            name='item_store_domain',
            field=models.CharField(default='', max_length=255, verbose_name='Домен магазина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='item_store_url',
            field=models.URLField(default='', verbose_name='Ссылка на товар в магазине'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='store_verified',
            field=models.BooleanField(default=False, verbose_name='Магазин проверен'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='item_category',
            field=models.CharField(choices=[('ELECTRONICS', 'Электроника'), ('CLOTHING', 'Одежда и обувь'), ('COSMETICS', 'Косметика и парфюмерия'), ('FOOD', 'Продукты питания'), ('BOOKS', 'Книги'), ('TOYS', 'Игрушки'), ('SPORTS', 'Спорт и отдых'), ('HOME', 'Товары для дома'), ('JEWELRY', 'Ювелирные изделия'), ('OTHER', 'Другое')], default='OTHER', max_length=64, verbose_name='Категория товара'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='item_store_domain',
            field=models.CharField(blank=True, default='', help_text='Домен магазина, извлеченный из URL', max_length=255, null=True, verbose_name='Домен магазина'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='item_store_url',
            field=models.URLField(blank=True, default='', help_text='Ссылка на страницу товара в официальном магазине/маркетплейсе', null=True, verbose_name='Ссылка на товар в магазине'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='store_verified',
            field=models.BooleanField(default=False, help_text='Магазин прошел проверку (авто или ручная)', verbose_name='Магазин проверен'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='store_link',
            field=models.URLField(blank=True, help_text='DEPRECATED: используйте item_store_url'),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address_full', models.TextField(help_text='Почтовый адрес или адрес ПВЗ', verbose_name='Полный адрес доставки')),
                ('country', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=32)),
                ('street', models.TextField(blank=True)),
                ('building', models.CharField(blank=True, max_length=32)),
                ('apartment', models.CharField(blank=True, max_length=32)),
                ('meeting_point', models.TextField(blank=True, help_text='Публичное место для личной передачи (для PERSONAL_HANDOVER)', verbose_name='Точка встречи')),
                ('delivery_mode', models.CharField(choices=[('INTERNATIONAL_MAIL', 'Международная почта'), ('DOMESTIC_MAIL', 'Внутренняя почта'), ('PERSONAL_HANDOVER', 'Личная передача'), ('PICKUP_POINT', 'Пункт выдачи (ПВЗ)')], default='INTERNATIONAL_MAIL', max_length=32, verbose_name='Способ доставки')),
                ('delivery_instructions', models.TextField(blank=True, help_text='Дополнительные инструкции от заказчика', verbose_name='Инструкции по доставке')),
                ('revealed_to_buyer', models.BooleanField(default=False, help_text='Адрес был раскрыт байеру после подтверждения покупки', verbose_name='Адрес раскрыт байеру')),
                ('revealed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата раскрытия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='core.orderrequest')),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shipping Addresses',
            },
        ),
        migrations.CreateModel(
            name='PurchaseConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_item_price_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Фактическая цена покупки')),
                ('item_photo_url', models.URLField(blank=True, help_text='URL к фотографии купленного товара', verbose_name='Фото товара')),
                ('receipt_photo_url', models.URLField(blank=True, help_text='URL к фотографии чека покупки', verbose_name='Фото чека')),
                ('receipt_store_name', models.CharField(blank=True, max_length=255, verbose_name='Название магазина из чека')),
                ('receipt_store_domain', models.CharField(blank=True, max_length=255, verbose_name='Домен магазина из чека')),
                ('receipt_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата покупки из чека')),
                ('receipt_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма из чека')),
                ('status', models.CharField(choices=[('PENDING', 'На проверке'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено'), ('NEEDS_REVIEW', 'Требуется ручная проверка')], default='PENDING', max_length=16, verbose_name='Статус проверки')),
                ('auto_check_passed', models.BooleanField(default=False, verbose_name='Автопроверка пройдена')),
                ('auto_check_details', models.TextField(blank=True, help_text='Лог автоматической проверки (сверка магазина, суммы и т.д.)', verbose_name='Детали автопроверки')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('review_notes', models.TextField(blank=True, verbose_name='Примечания модератора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_confirmation', to='core.deal')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
            ],
            options={
                'verbose_name': 'Purchase Confirmation',
                'verbose_name_plural': 'Purchase Confirmations',
            },
        ),
        migrations.CreateModel(
            name='OfficialStoreDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Например: amazon.com, wildberries.ru', max_length=255, unique=True, verbose_name='Домен')),
                ('store_name', models.CharField(max_length=255, verbose_name='Название магазина')),
                ('status', models.CharField(choices=[('VERIFIED', 'Проверен (разрешён)'), ('PENDING', 'На проверке (условно разрешён)'), ('REJECTED', 'Отклонён (чёрный список)')], default='PENDING', max_length=16, verbose_name='Статус проверки')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о магазине', verbose_name='Примечания')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_stores', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
            ],
            options={
                'verbose_name': 'Official Store Domain',
                'verbose_name_plural': 'Official Store Domains',
                'ordering': ['domain'],
            },
        ),
    ]
