# Generated by Django 3.2.25 on 2025-12-09 20:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20251209_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='actual_shipping_cost_rub',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость доставки по чеку (заполняется при отправке товара)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Фактическая стоимость доставки'),
        ),
        migrations.AddField(
            model_name='deal',
            name='buyer_reward_rub',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Вознаграждение байеру за покупку и доставку', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Вознаграждение байеру'),
        ),
        migrations.AddField(
            model_name='deal',
            name='country_from',
            field=models.CharField(blank=True, max_length=64, verbose_name='Страна покупки'),
        ),
        migrations.AddField(
            model_name='deal',
            name='country_to',
            field=models.CharField(blank=True, max_length=64, verbose_name='Страна получения'),
        ),
        migrations.AddField(
            model_name='deal',
            name='delivery_mode',
            field=models.CharField(blank=True, choices=[('PERSONAL_HANDOVER', 'Личная передача'), ('INTERNATIONAL_MAIL', 'Международная почта'), ('DOMESTIC_MAIL', 'Внутренняя почта')], help_text='Способ доставки товара (выбирается байером при создании сделки)', max_length=32, null=True, verbose_name='Режим доставки'),
        ),
        migrations.AddField(
            model_name='deal',
            name='shipping_budget_rub',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Зарезервированный бюджет на доставку (рассчитывается при создании сделки)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Бюджет на доставку'),
        ),
        migrations.AddField(
            model_name='deal',
            name='shipping_weight_category',
            field=models.CharField(blank=True, choices=[('UP_TO_1KG', 'До 1 кг'), ('FROM_1_TO_2KG', '1-2 кг'), ('FROM_2_TO_5KG', '2-5 кг'), ('FROM_5_TO_10KG', '5-10 кг'), ('OVER_10KG', 'Более 10 кг')], max_length=32, null=True, verbose_name='Категория веса/габарита'),
        ),
        migrations.AddField(
            model_name='deal',
            name='total_reserved_amount_rub',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сумма, которая должна быть зарезервирована с заказчика при оплате', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Общая сумма резервирования'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='allow_delivery_by_mail',
            field=models.BooleanField(default=True, help_text='Заказчик допускает доставку почтой/курьером', verbose_name='Разрешена доставка почтой'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='allow_personal_handover',
            field=models.BooleanField(default=True, help_text='Заказчик допускает личную передачу товара', verbose_name='Разрешена личная встреча'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='country_from',
            field=models.CharField(blank=True, help_text='Страна, где будет покупаться товар (ISO код, например: DE, FR)', max_length=64, verbose_name='Страна покупки'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='country_to',
            field=models.CharField(blank=True, help_text='Страна, куда будет доставлен товар (ISO код, например: RU)', max_length=64, verbose_name='Страна получения'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='shipping_weight_category',
            field=models.CharField(choices=[('UP_TO_1KG', 'До 1 кг'), ('FROM_1_TO_2KG', '1-2 кг'), ('FROM_2_TO_5KG', '2-5 кг'), ('FROM_5_TO_10KG', '5-10 кг'), ('OVER_10KG', 'Более 10 кг')], default='UP_TO_1KG', help_text='Категория веса/габарита для расчета стоимости доставки', max_length=32, verbose_name='Категория веса/габарита'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='buyer_fee_rub',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DEPRECATED: используйте buyer_reward_rub', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='deal',
            name='item_store_domain',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Домен магазина'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='item_store_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Ссылка на товар в магазине'),
        ),
    ]
