# Generated by Django 3.2.25 on 2025-12-10 07:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20251209_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='shipping_budget_ton',
            field=models.DecimalField(blank=True, decimal_places=9, default=Decimal('0E-9'), help_text='Бюджет на доставку в TON (конвертируется из shipping_budget_rub при создании сделки)', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0E-9'))], verbose_name='Бюджет на доставку в TON'),
        ),
    ]
