# Generated by Django 3.2.25 on 2025-12-10 08:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_deal_shipping_budget_ton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='delivery_mode',
        ),
        migrations.AddField(
            model_name='deal',
            name='remainder_rub',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Остаток средств после выплаты байеру (может быть возвращен заказчику или остаться у сервиса)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Остаток после выплаты'),
        ),
    ]
